repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/markdownlint/markdownlint
    rev: 99807515a6230ae113a5df389cb32181f21c2661  # frozen: v0.15.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/tillig/json-sort-cli
    rev: 2b7e147e0933bd30b58133b6f287e5c695ff4f0e # frozen: v3.0.1
    hooks:
      - id: json-sort
        args:
          - --autofix
